import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import { Toaster } from "@/components/shadcn/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/next.svg",
        type: "image/x-icon",
        sizes: "16x16",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/fonts/index.css"></link>
      </head>
      <body>
        <Layout>{children}</Layout>
        <Toaster />
      </body>
    </html>
  );
}


